#!/usr/bin/env bash
# 새 IP repo 부트스트랩 (30분 onboarding 목표).
#
# 사용:
#   seed-ip.sh <ip_name> <subsystem> <team> "<description>"
#
# 예:
#   seed-ip.sh pcie_phy host_ss host-team "PCIe Gen4 PHY (analog/digital)"
#
# 동작:
#   1) GitHub Enterprise 에 `ip-<name>` repo 생성 (gh repo create)
#   2) ip-template/ 를 변수 치환 후 push
#   3) branch protection 적용
#   4) manifest PR 자동 생성 (default.xml 에 <project> 추가)
#   5) 로컬 모드(--local) 에서는 1/3/4 를 로컬 bare repo + 파일 편집으로 시연.
set -euo pipefail

IP_NAME="${1:?usage: $0 <ip_name> <subsystem> <team> <description> [--local <workdir>]}"
SUBSYSTEM="${2:?subsystem required}"
TEAM="${3:?team required}"
IP_DESC="${4:?description required}"
MODE="${5:-remote}"
WORKDIR="${6:-/tmp/ssd-soc-seed-demo}"

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TEMPLATE="$ROOT/recommended/scaffolding/ip-template"

echo "[seed] preparing ip-$IP_NAME from template ..."
STAGE="$(mktemp -d)"
cp -r "$TEMPLATE"/. "$STAGE"

# 변수 치환
find "$STAGE" -type f \( -name "*.yaml" -o -name "*.md" -o -name "*.yml" -o -name "CODEOWNERS" \) -print0 |
  xargs -0 sed -i.bak \
    -e "s/\${IP_NAME}/$IP_NAME/g" \
    -e "s|\${IP_DESCRIPTION}|$IP_DESC|g" \
    -e "s/\${SUBSYSTEM}/$SUBSYSTEM/g" \
    -e "s/\${TEAM}/$TEAM/g"
find "$STAGE" -name "*.bak" -delete

# Seed stub RTL/SIM from scaffold catalog (if exists)
# (rtl/.gitkeep 자리에 minimal stub 을 만들어 빈 디렉터리 회피)
cat > "$STAGE/rtl/${IP_NAME}.sv" <<EOF
// SPDX-License-Identifier: Apache-2.0
module ${IP_NAME} (input logic clk, input logic rst_n);
  initial \$display("[STUB] %m");
endmodule
EOF
cat > "$STAGE/sim/tb_${IP_NAME}.sv" <<EOF
\`timescale 1ns/1ps
module tb_${IP_NAME};
  logic clk=0, rst_n=0; always #5 clk=~clk;
  initial begin #20 rst_n=1; #100 \$display("[tb] ok"); \$finish; end
  ${IP_NAME} dut(.clk(clk), .rst_n(rst_n));
endmodule
EOF
rm -f "$STAGE/rtl/.gitkeep" "$STAGE/sim/.gitkeep" "$STAGE/cfg/.gitkeep" "$STAGE/doc/.gitkeep"

# Initial commit
( cd "$STAGE"
  git init -q
  git checkout -q -b main
  git -c user.email=ci@acme-ssd -c user.name="ssd-soc-bot" add -A
  git -c user.email=ci@acme-ssd -c user.name="ssd-soc-bot" commit -q -m "init: $IP_NAME ($SUBSYSTEM/$TEAM)"
)

if [ "$MODE" = "--local" ]; then
  REMOTES="$WORKDIR/remotes"
  mkdir -p "$REMOTES"
  git init -q --bare "$REMOTES/ip-$IP_NAME.git"
  ( cd "$STAGE"
    git remote add origin "$REMOTES/ip-$IP_NAME.git"
    git push -q origin main
  )
  echo "[seed] local bare repo at: $REMOTES/ip-$IP_NAME.git"
  echo "[seed] (manifest PR step skipped in --local mode — see local-bootstrap.sh)"
else
  # Remote mode: GitHub Enterprise
  REPO="acme-ssd/ip-$IP_NAME"
  echo "[seed] creating GitHub repo $REPO ..."
  gh repo create "$REPO" --private --description "$IP_DESC" || true
  ( cd "$STAGE"
    git remote add origin "git@github.com:$REPO.git"
    git push -q -u origin main
  )
  echo "[seed] applying branch protection ..."
  "$ROOT/recommended/scaffolding/apply-branch-protection.sh" "$REPO"

  echo "[seed] opening manifest PR to add <project name=\"ip-$IP_NAME\" .../>"
  MFST_REPO="$(mktemp -d)"
  gh repo clone acme-ssd/ssd-soc-manifest "$MFST_REPO" -- -q
  ( cd "$MFST_REPO"
    BRANCH="add/ip-$IP_NAME"
    git checkout -q -b "$BRANCH"
    python3 "$ROOT/tools/manifest_bump.py" add-ip \
        --manifest default.xml --name "ip-$IP_NAME" --path "ip/$IP_NAME" --subsystem "$SUBSYSTEM"
    git -c user.email=ci@acme-ssd -c user.name="ssd-soc-bot" commit -aq -m "add ip-$IP_NAME"
    git push -q -u origin "$BRANCH"
    gh pr create --fill --title "manifest: add ip-$IP_NAME" --body "Auto-generated by seed-ip.sh"
  )
fi

rm -rf "$STAGE"
echo "[seed] done. ip-$IP_NAME bootstrapped."
