+incdir+ssd_soc/common/pkg
+incdir+ssd_soc/common/interfaces
ssd_soc/common/interfaces/axi_if.sv
ssd_soc/common/interfaces/apb_if.sv
ssd_soc/common/pkg/ssd_soc_pkg.svh
ssd_soc/subsystems/host_ss/ip/pcie_phy/rtl/pcie_phy.sv
ssd_soc/subsystems/host_ss/ip/pcie_ctrl/rtl/pcie_ctrl.sv
ssd_soc/subsystems/host_ss/ip/nvme_cmd_proc/rtl/nvme_cmd_proc.sv
ssd_soc/subsystems/host_ss/ip/host_dma/rtl/host_dma.sv
ssd_soc/subsystems/host_ss/ip/pcie_cfg/rtl/pcie_cfg.sv
ssd_soc/subsystems/host_ss/rtl/host_ss.sv
ssd_soc/subsystems/fcc_ss/ip/nand_phy/rtl/nand_phy.sv
ssd_soc/subsystems/fcc_ss/ip/nand_ctrl/rtl/nand_ctrl.sv
ssd_soc/subsystems/fcc_ss/ip/ldpc_codec/rtl/ldpc_codec.sv
ssd_soc/subsystems/fcc_ss/ip/flash_dma/rtl/flash_dma.sv
ssd_soc/subsystems/fcc_ss/ip/bbm/rtl/bbm.sv
ssd_soc/subsystems/fcc_ss/rtl/fcc_ss.sv
ssd_soc/subsystems/mem_ss/ip/ddr4_ctrl/rtl/ddr4_ctrl.sv
ssd_soc/subsystems/mem_ss/ip/ddr4_phy/rtl/ddr4_phy.sv
ssd_soc/subsystems/mem_ss/ip/sram_scratchpad/rtl/sram_scratchpad.sv
ssd_soc/subsystems/mem_ss/ip/axi_interconnect/rtl/axi_interconnect.sv
ssd_soc/subsystems/mem_ss/ip/mem_arb/rtl/mem_arb.sv
ssd_soc/subsystems/mem_ss/rtl/mem_ss.sv
ssd_soc/subsystems/cpu_ss/ip/riscv_core/rtl/riscv_core.sv
ssd_soc/subsystems/cpu_ss/ip/icache/rtl/icache.sv
ssd_soc/subsystems/cpu_ss/ip/dcache/rtl/dcache.sv
ssd_soc/subsystems/cpu_ss/ip/debug_module/rtl/debug_module.sv
ssd_soc/subsystems/cpu_ss/ip/irq_ctrl/rtl/irq_ctrl.sv
ssd_soc/subsystems/cpu_ss/rtl/cpu_ss.sv
ssd_soc/subsystems/sec_ss/ip/aes_engine/rtl/aes_engine.sv
ssd_soc/subsystems/sec_ss/ip/sha_engine/rtl/sha_engine.sv
ssd_soc/subsystems/sec_ss/ip/trng/rtl/trng.sv
ssd_soc/subsystems/sec_ss/ip/secure_boot_rom/rtl/secure_boot_rom.sv
ssd_soc/subsystems/sec_ss/ip/key_store/rtl/key_store.sv
ssd_soc/subsystems/sec_ss/rtl/sec_ss.sv
ssd_soc/top/rtl/ssd_soc_top.sv
