#!/usr/bin/env python3
"""
sync_codeowners.py — ip.yaml ↔ CODEOWNERS 드리프트 감지 및 교정.

운영 모델:
  - ip.yaml 의 owner/backup/reviewers 가 single source of truth.
  - CODEOWNERS 는 본 도구가 매 PR 마다 ip.yaml 로부터 재생성.
  - CI 의 'codeowners-drift' job 이 본 도구를 `--check` 로 실행해 어긋남이 있으면
    PR을 fail 시키고 자동 fix-up 커밋을 제안.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# 자체 minimal YAML (bom.py 와 동일 — 작은 의존성)
sys.path.insert(0, str(Path(__file__).parent))
from bom import parse_simple_yaml  # type: ignore


TEMPLATE = """\
# Generated by tools/sync_codeowners.py — DO NOT EDIT MANUALLY.
# Source of truth: ip.yaml (owner, backup, reviewers).

*                       {owner}{backup_part}
ip.yaml                 {owner} @acme-ssd/integration-team
.github/workflows/      @acme-ssd/platform-team
LICENSE                 @acme-ssd/legal-team
{reviewer_lines}"""


def render(meta: dict) -> str:
    owner = meta.get("owner", "@acme-ssd/integration-team")
    backup = meta.get("backup")
    reviewers = meta.get("reviewers") or []
    lines = ""
    if reviewers:
        lines = "\n# Additional required reviewers (from ip.yaml `reviewers:`)\n"
        for r in reviewers:
            lines += f"*                       {r}\n"
    return TEMPLATE.format(
        owner=owner,
        backup_part=f" {backup}" if backup else "",
        reviewer_lines=lines,
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo",  required=True, help="path to IP repo root")
    ap.add_argument("--check", action="store_true", help="exit 1 if drift detected")
    args = ap.parse_args()

    root = Path(args.repo)
    ipyaml = root / "ip.yaml"
    if not ipyaml.is_file():
        # Phase A style
        cfg = root / "cfg"
        if cfg.is_dir():
            for f in cfg.iterdir():
                if f.name.endswith(".ip.yaml"):
                    ipyaml = f; break
    if not ipyaml.is_file():
        print(f"::warning::no ip.yaml under {root}")
        return 0

    meta = parse_simple_yaml(ipyaml.read_text())
    expected = render(meta)

    co_path = root / "CODEOWNERS"
    actual = co_path.read_text() if co_path.exists() else ""

    if expected.strip() == actual.strip():
        print(f"[ok ] CODEOWNERS in sync with {ipyaml}")
        return 0

    if args.check:
        print(f"::error::CODEOWNERS drift in {root}. Run sync_codeowners.py without --check to fix.")
        return 1

    co_path.write_text(expected)
    print(f"[fix] CODEOWNERS rewritten in {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
